version: '3'
services:
  app: 
    build: .
    container_name: "app"
    restart: unless-stopped
    environment:
      - "DB_PATH=mongodb://mongo:27017/nanos"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports: 
      - "8000:3000"
    depends_on: 
      - "mongo"
    links:
      - "mongo"
  mongo:
    image: "mongo:4"
    container_name: "mongo"
    restart: unless-stopped
    environment:
      - "MONGO_DATA_DIR=/data/db"
    volumes:
        - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod